/**
 * `npm run gen:supabase-migration`
 *
 * Writes the Postgres half of the schema to `supabase/migrations/`, generated
 * from the same declarations `src/db/migrations.ts` uses for SQLite. The file
 * is committed so the migration history is reviewable, but it is never edited
 * by hand: change a table declaration and add a new migration, then run this
 * again.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { releaseOneTables } from '../src/data/schema/tables/all';
import { toPostgres } from '../src/data/schema/to-postgres';

const OUT_DIR = join(process.cwd(), 'supabase', 'migrations');
const FILE_NAME = '20260809000000_core_data_model.sql';

const header = `-- Core data model for CalSnap (spec 0002).
--
-- GENERATED by \`npm run gen:supabase-migration\` from the table declarations
-- in src/data/schema/. Do not edit this file by hand: the SQLite migration in
-- src/db/migrations.ts comes from the same declarations, and editing one side
-- here is exactly the drift the generator exists to prevent.
--
-- Row level security is enabled AND forced on every table, with one policy
-- testing user_id and an index on user_id because that policy runs on every
-- row touched. auth.uid() is wrapped in a select so Postgres evaluates it
-- once per statement rather than once per row.

`;

mkdirSync(OUT_DIR, { recursive: true });
const path = join(OUT_DIR, FILE_NAME);
writeFileSync(path, header + toPostgres(releaseOneTables), 'utf8');

console.log(`Wrote ${path}`);
