/**
 * `npm run gen:supabase-migration`
 *
 * Writes the Postgres half of the schema to `supabase/migrations/`, generated
 * from the same declarations `src/db/migrations.ts` uses for SQLite. The files
 * are committed so the migration history is reviewable, but they are never
 * edited by hand: change a table declaration and add a new migration, then run
 * this again.
 *
 * **Two files, and the split is deliberate.** Each migration here is rewritten
 * in place on every run, so a file that has already been applied must keep
 * generating byte for byte what was applied. Adding new statements to an old
 * file would rewrite history instead of extending it. So a later change gets
 * its own emitter and its own file, as spec 0005 did.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { releaseOneTables } from '../src/data/schema/tables/all';
import { toPostgres, toPostgresSyncTriggers } from '../src/data/schema/to-postgres';

const OUT_DIR = join(process.cwd(), 'supabase', 'migrations');

const coreHeader = `-- Core data model for CalSnap (spec 0002, identity per spec 0004).
--
-- GENERATED by \`npm run gen:supabase-migration\` from the table declarations
-- in src/data/schema/. Do not edit this file by hand: the SQLite migration in
-- src/db/migrations.ts comes from the same declarations, and editing one side
-- here is exactly the drift the generator exists to prevent.
--
-- Row level security is enabled AND forced on every table, with one policy
-- testing user_id and an index on user_id because that policy runs on every
-- row touched. Identity is the Clerk token's sub claim, so user_id is text
-- and every policy reads auth.jwt(). The claim is wrapped in a select so
-- Postgres evaluates it once per statement rather than once per row.

`;

const arbitrationHeader = `-- Sync arbitration for CalSnap (spec 0005).
--
-- GENERATED by \`npm run gen:supabase-migration\`. Do not edit by hand.
--
-- Spec 0002 said the server assigns updated_at and that a deleted row is never
-- revived. Nothing implemented either, so the stored updated_at was whatever
-- the pushing phone sent, and the tombstone rule lived only in client code.
-- Because pullChanges pages on updated_at, a phone with a slow clock pushed
-- rows stamped behind another device's watermark and that device never pulled
-- them: a meal simply missing, both phones online, nothing failing.
--
-- One clock, owned here, removes that at the source. It also collapses the
-- arbitration rule to one sentence, the last push wins, because once the
-- server stamps there is nothing left to compare.

`;

mkdirSync(OUT_DIR, { recursive: true });

const files: readonly (readonly [string, string])[] = [
  ['20260809000000_core_data_model.sql', coreHeader + toPostgres(releaseOneTables)],
  [
    '20260810000000_sync_arbitration.sql',
    arbitrationHeader + toPostgresSyncTriggers(releaseOneTables),
  ],
];

for (const [name, body] of files) {
  const path = join(OUT_DIR, name);
  writeFileSync(path, body, 'utf8');
  console.log(`Wrote ${path}`);
}
