-- Manual daily calorie targets for CalSnap (spec 0006).
--
-- GENERATED by `npm run gen:supabase-migration`. Do not edit by hand.
--
-- A target the person set themselves, applying from one local date forward. It
-- never rewrites a daily_targets row that already exists; it changes what a
-- later day's row is created from.
--
-- Its own file because the two before it are applied, and a file here is
-- rewritten in full on every run, so an applied one must keep generating
-- exactly what was applied.
--
-- Note what is NOT here: onboarding_draft is presence 'sqlite', so it never
-- reaches Postgres and never enters a push. The partial answers of an
-- unfinished setup stay on the one device that is giving them.
--
-- The trigger functions are repeated as `create or replace` and are byte for
-- byte the ones the arbitration migration already applied, so re-running them
-- changes nothing. The new trigger below is what target_overrides gains: the
-- sticky delete variant, because it declares a tombstone.

create table public.target_overrides (
  id uuid not null,
  user_id text not null,
  effective_from date not null,
  calories integer not null check (calories > 0),
  created_at timestamptz not null,
  updated_at timestamptz not null,
  deleted_at timestamptz,
  primary key (id)
);
create index target_overrides_user_effective_from_idx on public.target_overrides (user_id, effective_from);
create index target_overrides_user_id_idx on public.target_overrides (user_id);

alter table public.target_overrides enable row level security;
alter table public.target_overrides force row level security;

create policy target_overrides_own_rows on public.target_overrides
  for all to authenticated
  using      (user_id = (select auth.jwt() ->> 'sub'))
  with check (user_id = (select auth.jwt() ->> 'sub'));

create or replace function public.sync_stamp()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' then
    -- Frozen, never restamped. `saveMeal` gives a meal and all of its items
    -- one identical `created_at`, and `searchPastItems` orders on it, but a
    -- meal and its items are pushed in separate statements. A server stamp
    -- would split the instant they deliberately share.
    new.created_at := old.created_at;
  end if;

  new.updated_at := clock_timestamp();
  return new;
end;
$$;

create or replace function public.sync_stamp_sticky_delete()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' then
    if old.deleted_at is not null and new.deleted_at is null then
      return old;
    end if;

    new.created_at := old.created_at;
  end if;

  new.updated_at := clock_timestamp();
  return new;
end;
$$;

create trigger target_overrides_sync_stamp
  before insert or update on public.target_overrides
  for each row execute function public.sync_stamp_sticky_delete();
