-- Core data model for CalSnap (spec 0002).
--
-- GENERATED by `npm run gen:supabase-migration` from the table declarations
-- in src/data/schema/. Do not edit this file by hand: the SQLite migration in
-- src/db/migrations.ts comes from the same declarations, and editing one side
-- here is exactly the drift the generator exists to prevent.
--
-- Row level security is enabled AND forced on every table, with one policy
-- testing user_id and an index on user_id because that policy runs on every
-- row touched. auth.uid() is wrapped in a select so Postgres evaluates it
-- once per statement rather than once per row.

create table public.profiles (
  user_id uuid not null references auth.users(id) on delete cascade,
  age_years integer not null check (age_years between 13 and 120),
  age_recorded_on date not null,
  sex text not null check (sex in ('female', 'male')),
  height_cm numeric(5,1) not null check (height_cm > 0),
  activity_level text not null check (activity_level in ('sedentary', 'light', 'moderate', 'active', 'very_active')),
  goal_direction text not null check (goal_direction in ('lose', 'hold', 'gain')),
  goal_rate_kg_per_week numeric(3,2) not null default 0 check (goal_rate_kg_per_week between 0 and 1.5),
  goal_weight_kg numeric(5,2),
  unit_preference text not null default 'metric' check (unit_preference in ('metric', 'imperial')),
  timezone text not null,
  exercise_credit text not null default 'full' check (exercise_credit in ('none', 'full', 'partial')),
  exercise_credit_factor numeric(3,2) not null default 1 check (exercise_credit_factor between 0 and 1),
  photo_sync_enabled boolean not null default false,
  consented_at timestamptz,
  consent_version text,
  onboarded_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  primary key (user_id)
);

alter table public.profiles enable row level security;
alter table public.profiles force row level security;

create policy profiles_own_rows on public.profiles
  for all to authenticated
  using      (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create table public.meal_scans (
  id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  model text not null,
  prompt_version text not null,
  status text not null check (status in ('ok', 'low_confidence', 'unrecognised', 'failed')),
  confidence text check (confidence in ('high', 'medium', 'low')),
  raw_response jsonb,
  cost_cents numeric(6,3),
  created_at timestamptz not null,
  updated_at timestamptz not null,
  primary key (id)
);
create index meal_scans_user_created_at_idx on public.meal_scans (user_id, created_at);
create index meal_scans_user_id_idx on public.meal_scans (user_id);

alter table public.meal_scans enable row level security;
alter table public.meal_scans force row level security;

create policy meal_scans_own_rows on public.meal_scans
  for all to authenticated
  using      (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create table public.meals (
  id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  eaten_on date not null,
  eaten_at timestamptz not null,
  tz_at_save text not null,
  meal_type text not null check (meal_type in ('breakfast', 'lunch', 'dinner', 'snack')),
  meal_type_source text not null check (meal_type_source in ('guessed', 'chosen')),
  note text,
  photo_local_uri text,
  photo_remote_path text,
  photo_synced_at timestamptz,
  scan_id uuid references public.meal_scans(id) on delete set null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  deleted_at timestamptz,
  primary key (id)
);
create index meals_user_eaten_on_live_idx on public.meals (user_id, eaten_on) where deleted_at is null;
create index meals_scan_id_idx on public.meals (scan_id);
create index meals_user_id_idx on public.meals (user_id);

alter table public.meals enable row level security;
alter table public.meals force row level security;

create policy meals_own_rows on public.meals
  for all to authenticated
  using      (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create table public.meal_items (
  id uuid not null,
  meal_id uuid not null references public.meals(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  position integer not null,
  base_per numeric(6,1) not null default 100,
  base_unit text not null check (base_unit in ('g', 'ml', 'piece')),
  base_calories integer not null check (base_calories >= 0),
  base_protein_g numeric(6,1) not null check (base_protein_g >= 0),
  base_carbs_g numeric(6,1) not null check (base_carbs_g >= 0),
  base_fat_g numeric(6,1) not null check (base_fat_g >= 0),
  quantity numeric(7,1) not null check (quantity > 0),
  calories integer not null check (calories >= 0),
  protein_g numeric(6,1) not null check (protein_g >= 0),
  carbs_g numeric(6,1) not null check (carbs_g >= 0),
  fat_g numeric(6,1) not null check (fat_g >= 0),
  source text not null check (source in ('ai_scan', 'manual', 'ai_edited')),
  edited_fields text,
  confidence text check (confidence in ('high', 'medium', 'low')),
  created_at timestamptz not null,
  updated_at timestamptz not null,
  deleted_at timestamptz,
  primary key (id)
);
create index meal_items_meal_id_idx on public.meal_items (meal_id);
create index meal_items_user_id_idx on public.meal_items (user_id);
create index meal_items_user_name_lower_idx on public.meal_items (user_id, lower(name));

alter table public.meal_items enable row level security;
alter table public.meal_items force row level security;

create policy meal_items_own_rows on public.meal_items
  for all to authenticated
  using      (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create table public.daily_targets (
  id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  on_date date not null,
  calories integer not null check (calories > 0),
  protein_g numeric(6,1),
  carbs_g numeric(6,1),
  fat_g numeric(6,1),
  source text not null check (source in ('computed', 'manual')),
  formula_version text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  deleted_at timestamptz,
  primary key (id)
);
create unique index daily_targets_user_on_date_live_idx on public.daily_targets (user_id, on_date) where deleted_at is null;
create index daily_targets_user_on_date_idx on public.daily_targets (user_id, on_date);
create index daily_targets_user_id_idx on public.daily_targets (user_id);

alter table public.daily_targets enable row level security;
alter table public.daily_targets force row level security;

create policy daily_targets_own_rows on public.daily_targets
  for all to authenticated
  using      (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create table public.weight_entries (
  id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  on_date date not null,
  recorded_at timestamptz not null,
  weight_kg numeric(5,2) not null check (weight_kg between 20 and 500),
  source text not null check (source in ('onboarding', 'manual')),
  created_at timestamptz not null,
  updated_at timestamptz not null,
  deleted_at timestamptz,
  primary key (id)
);
create unique index weight_entries_user_on_date_live_idx on public.weight_entries (user_id, on_date) where deleted_at is null;
create index weight_entries_user_on_date_idx on public.weight_entries (user_id, on_date);
create index weight_entries_user_id_idx on public.weight_entries (user_id);

alter table public.weight_entries enable row level security;
alter table public.weight_entries force row level security;

create policy weight_entries_own_rows on public.weight_entries
  for all to authenticated
  using      (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));
