-- Sync arbitration for CalSnap (spec 0005).
--
-- GENERATED by `npm run gen:supabase-migration`. Do not edit by hand.
--
-- Spec 0002 said the server assigns updated_at and that a deleted row is never
-- revived. Nothing implemented either, so the stored updated_at was whatever
-- the pushing phone sent, and the tombstone rule lived only in client code.
-- Because pullChanges pages on updated_at, a phone with a slow clock pushed
-- rows stamped behind another device's watermark and that device never pulled
-- them: a meal simply missing, both phones online, nothing failing.
--
-- One clock, owned here, removes that at the source. It also collapses the
-- arbitration rule to one sentence, the last push wins, because once the
-- server stamps there is nothing left to compare.

create or replace function public.sync_stamp()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' then
    -- Frozen, never restamped. `saveMeal` gives a meal and all of its items
    -- one identical `created_at`, and `searchPastItems` orders on it, but a
    -- meal and its items are pushed in separate statements. A server stamp
    -- would split the instant they deliberately share.
    new.created_at := old.created_at;
  end if;

  new.updated_at := clock_timestamp();
  return new;
end;
$$;

create or replace function public.sync_stamp_sticky_delete()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' then
    if old.deleted_at is not null and new.deleted_at is null then
      return old;
    end if;

    new.created_at := old.created_at;
  end if;

  new.updated_at := clock_timestamp();
  return new;
end;
$$;

create trigger profiles_sync_stamp
  before insert or update on public.profiles
  for each row execute function public.sync_stamp();

create trigger meal_scans_sync_stamp
  before insert or update on public.meal_scans
  for each row execute function public.sync_stamp();

create trigger meals_sync_stamp
  before insert or update on public.meals
  for each row execute function public.sync_stamp_sticky_delete();

create trigger meal_items_sync_stamp
  before insert or update on public.meal_items
  for each row execute function public.sync_stamp_sticky_delete();

create trigger daily_targets_sync_stamp
  before insert or update on public.daily_targets
  for each row execute function public.sync_stamp_sticky_delete();

create trigger weight_entries_sync_stamp
  before insert or update on public.weight_entries
  for each row execute function public.sync_stamp_sticky_delete();
